name: streamlit
channels:
  - conda-forge
dependencies:
  - python=3.10.4
  - setuptools=61.2.0
  - sqlite=3.38.5
  - tk=8.6.12
  - wheel=0.37.1
  - zlib=1.2.12
  - streamlit >= 0.73
  - dlib
  - numpy
  - click
  - opencv
  # - streamlit_webrtc