name: streamlit
channels:
  - defaults
dependencies:
  - python=3.10.4
  - setuptools=61.2.0
  - sqlite=3.38.5
  - tk=8.6.12
  - vc=14.2
  - vs2015_runtime
  - wheel=0.37.1
  - wincertstore=0.2
  - zlib=1.2.12
  - pip:
    - aioice==0.7.6
    - aiortc==1.3.2
    - altair==4.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - av==9.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - blinker==1.4
    - cachetools==5.2.0
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - click==8.1.3
    - colorama==0.4.5
    - commonmark==0.9.1
    - cryptography==37.0.4
    - cycler==0.11.0
    - debugpy==1.6.2
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dlib==19.24.0
    - dnspython==2.2.1
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - fonttools==4.34.4
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-crc32c==1.3.0
    - idna==3.3
    - importlib-metadata==4.12.0
    - ipykernel==6.15.1
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonschema==4.7.2
    - jupyter-client==7.3.4
    - jupyter-core==4.11.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.1
    - kiwisolver==1.4.4
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - netifaces==0.11.0
    - notebook==6.4.12
    - numpy==1.23.1
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - packaging==21.3
    - pandas==1.4.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pickleshare==0.7.5
    - pillow==9.2.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.30
    - protobuf==3.20.1
    - psutil==5.9.1
    - pure-eval==0.2.2
    - pyarrow==8.0.0
    - pycparser==2.21
    - pydeck==0.7.1
    - pydub==0.25.1
    - pyee==9.0.4
    - pygments==2.12.0
    - pylibsrtp==0.7.1
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pytz-deprecation-shim==0.1.0.post0
    - pywin32==304
    - pywinpty==2.0.6
    - pyzmq==23.2.0
    - requests==2.28.1
    - rich==12.5.1
    - semver==2.13.0
    - send2trash==1.8.0
    - six==1.16.0
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - stack-data==0.3.0
    - streamlit==1.10.0
    - streamlit-webrtc==0.42.0
    - terminado==0.15.0
    - tinycss2==1.1.1
    - toml==0.10.2
    - toolz==0.12.0
    - tornado==6.2
    - traitlets==5.3.0
    - typing-extensions==4.3.0
    - tzdata==2022.1
    - tzlocal==4.2
    - urllib3==1.26.10
    - validators==0.20.0
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.1
    - zipp==3.8.1
